### ISSUE TITLE
Need asterisks in appendix?

### ISSUE THREAD

**Issue by adrn** [smoh/gaia-comoving-stars#30]
Double check that the mu_alpha's in the appendix are consistent with definitions above (e.g., https://github.com/smoh/gaia-comoving-stars/blob/master/paper/ms.tex#L922)

**Comment by smoh** [comment]
Fixed.


On April 16, 2017 at 4:35:48 PM, Adrian Price-Whelan (
notifications@github.com) wrote:

Double check that the mu_alpha's in the appendix are consistent with
definitions above (e.g.,
https://github.com/smoh/gaia-comoving-stars/blob/master/paper/ms.tex#L922)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/smoh/gaia-comoving-stars/issues/30>, or mute the thread
